name: ESLint

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - dev

jobs:
  eslint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install ESLint
        run: npm install --save-dev eslint

      - name: Run ESLint
        run: npx eslint .
