name: Lint

on:
  pull_request:
    branches:
      - dev

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Run Prettier
        run: npx prettier --check .

      - name: Run ESLint
        run: npx eslint .
