name: TypeCheck

on:
  pull_request:
    branches:
      - dev

jobs:
  type-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: npm install

      - name: Run TypeCheck
        run: npm run type-check

